name: Python Pull Request Validation Workflow

on:
    pull_request:
        branches: [ "main", "master" ]

jobs:
  Validation:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Python 3.12
        uses: actions/setup-python@v2
        with:
          python-version: "3.13"
          architecture: "x64"

      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install uv
          uv venv
          uv pip install -e .[dev]

      - name: Python Run Tests
        run: |
          uv run pytest -v
